name: CI

on:
  push:
    branches: [ "main" ]
    
env:
      SSH_KEY: ${{secrets.SSH_KEY}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 16
          uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: 'npm'
        - run: npm install
        - name: build
          working-directory: ./todo
          run: npm build
        - run: mkdir ~/.ssh
        - run: 'echo "$SSH_KEY" >> ~/.ssh/github-action'
        - run: chmod 400 ~/.ssh/github-action
        - run: echo -e "Host gauser\n\tUser gauser\n\tHostname 174.137.49.209\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config
        - run: rsync -e ssh public gauser:~/static
        - name: upload static file
          working-directory: ./todo
          run: rsync -e ssh build/app.js gauser:~/static/js/app.js
