name: CI

on:
  push:
    branches: [ "main" ]
    
env:
      SSH_KEY: ${{secrets.SSH_KEY}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todo
    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 16
          uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: 'npm'
            cache-dependency-path: ./todo/package-lock.json
        - run: npm install
        - name: build
          run: npm run build
        - run: mkdir ~/.ssh
        - run: 'echo "$SSH_KEY" >> ~/.ssh/github-action'
        - run: chmod 400 ~/.ssh/github-action
        - run: echo -e "Host gauser\n\tUser gauser\n\tHostname 174.137.49.209\n\tPort 26392\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config
        - run: rsync -e ssh public gauser:~/static
        - name: upload static file
          run: rsync -e ssh -a build/static/ gauser:~/static/
